units:
  kx: cx
  ky: cy

  px: kx + 2.5
  py: ky + 2.5

  dx: kx + 2
  dy: ky + 2

  buff: 9.75
  buffs: 10

  controllerW: 18.5
  controllerH: 33.5
  belowControllerH: 17
  caseBorder: 1.5
  screwThreadRadius: 0.5
  screwPCBRadius: 4.0

points:
  zones:
    matrix:
      key:
        padding: ky + 2
        spread: kx + 2
      columns:
        h:
          key:
            column_net: P017
          rows.utility.skip: true
          rows.anchor:
            name: utility
            ref: matrix_h_down
            shift: [5,-76]
            width: 1.5u
            row_net: P029
        j:
          rows.utility.skip: true
          key:
            column_net: P011
        k:
          key:
            stagger: 8
            column_net: P100
        l:
          key:
            stagger: -8
            column_net: P024
        semi:
          key:
            stagger: -9.5
            column_net: P022
        apos:
          key:
            stagger: 9.5
            column_net: P020
        enter:
          key: 
            column_net: P008
      rows:
        utility:
          row_net: P029
        down:
          row_net: P002
        home:
          row_net: P115
        up:
          row_net: P113
      anchor: 
        shift: [100,-150]
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px - 4,py - 4]
  keys:
    - what: rectangle
      where: true
      size: [14,14]
  board:
    - what: polygon
      operation: stack
      fillet: 0
      points:
        - ref: matrix_h_up
          shift: [-.5px,.5py]
        - ref: matrix_j_up
          shift: [buff,.5py]
        - ref: matrix_k_up
          shift: [-.5px,.5py]
        - ref: matrix_k_up
          shift: [.5px,.5py]
        - ref: matrix_l_up
          shift: [-buff,.5py]
#        - ref: matrix_l_up
#          shift: [.5px,.5py]
#        - ref: matrix_semi_up
#          shift: [-buff,.5py]
#        - ref: matrix_semi_up
#          shift: [buff,.5py]
#        - ref: matrix_apos_up
#          shift: [-.5px,.5py]
        - ref: matrix_enter_up
          shift: [.5px,.5py]
        - ref: matrix_enter_utility
          shift: [.5px,-.5py]
        - ref: matrix_apos_utility
          shift: [-buff,-.5py]
        - ref: matrix_semi_utility
          shift: [.5px,-.5py]
        - ref: matrix_semi_utility
          shift: [-.5px,-.5py]
        - ref: matrix_l_utility
          shift: [buff,-.5py]
        - ref: matrix_l_utility
          shift: [-.5px,-.5py]
      #  - ref: matrix_k_utility
        #  shift: [buff, -.5py]
      #  - ref: matrix_k_utility
        #  shift: [-buff, -.5py]
        - ref: matrix_h_down
          shift: [-.5px,-.5py - cy - 2]
  right_combo:
    - name: board
    - operation: subtract
      name: keys
  chip: 
    - what: polygon
      operation: stack

      points:
        - ref: matrix_h_up
          shift: [-.5dx,.5dy]
        - ref: matrix_j_up
          shift: [buffs,.5dy]
        - ref: matrix_k_up
          shift: [-.5dx,.5dy]
        - ref: matrix_k_up
          shift: [.5dx,.5dy]
        - ref: matrix_l_up
          shift: [-buffs,.5dy]
#        - ref: matrix_l_up
#          shift: [.5dx,.5dy]
#        - ref: matrix_semi_up
#          shift: [-buffs,.5dy]
#        - ref: matrix_semi_up
#          shift: [buffs,.5dy]
#        - ref: matrix_apos_up
#          shift: [-.5dx,.5dy]
        - ref: matrix_enter_up
          shift: [.5dx,.5dy]
        - ref: matrix_enter_utility
          shift: [.5dx,-.5dy]
        - ref: matrix_apos_utility
          shift: [-buffs,-.5dy]
        - ref: matrix_semi_utility
          shift: [.5dx,-.5dy]
        - ref: matrix_semi_utility
          shift: [-.5dx,-.5dy]
        - ref: matrix_l_utility
          shift: [buffs,-.5dy]
        - ref: matrix_l_utility
          shift: [-.5dx,-.5dy]
      #  - ref: matrix_k_utility
        #  shift: [buffs, -.5dy]
      #  - ref: matrix_k_utility
        #  shift: [-buffs, -.5dy]
        - ref: matrix_h_down
          shift: [-.5dx,-.5dy - cy - 2]

pcbs: 
  right:
    outlines:
      main:
        outline: chip
    footprints:
      choc_hot:
        what: choc
        where: true
        params: 
          keycaps: true
          reverse: false
          hotswap: true
          from: '{{column_net}}'
          to: '{{colrow}}'
        adjust: 
          rotate: 180
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [8.3,-2.5]
          rotate: 90
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where: 
          ref: matrix_h_up
          shift: [8,-1.5]
          rotate: 0
      switch:
        what: slider
        where:
          ref: utility
          shift: [-13,5]
          rotate: 90
        params: 
          side: B
          from: pos
          to: RAW
      reset_button:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: utility
          shift: [-13,-4]
          rotate: 90
      battery_jack:
        what: jstph
        where: 
          ref: matrix_k_home
          shift: [0,6]
          rotate: -90
        params:
          side: B
          pos: pos
          neg: GND
      screw_bottom_left:
        what: mountinghole
        where:
          ref: matrix_enter_utility
          shift: [-10,8.5]
      screw_top_left:
        what: mountinghole
        where:
          ref: matrix_enter_up
          shift: [-10,-10.5]
      screw_middle:
        what: mountinghole
        where: 
          ref: matrix_l_down
          shift: [.5px - 1,.5py - .5]
      screw_bottom_right:
        what: mountinghole
        where: 
          ref: matrix_j_down
          shift: [-3.5,-14]
      screw_top_right:
        what: mountinghole
        where:
          ref: matrix_j_home
          shift: [8,8]
      front_text:
        what: text
        where: &textWhere
          ref: matrix_semi_up
          shift: [0,.5py + 2]
        params: &textParams
          text: Silikeys
          justify: bottom
          h_size: 3.0
          v_size: 3.0
          thickness: 0.4