units:
  kx: cx
  ky: cy

  px: kx + 2.5
  py: ky + 2.5

  dx: kx + 2
  dy: ky + 2

  buff: 9.75
  buffs: 10

  controllerW: 18.5
  controllerH: 33.5
  belowControllerH: 17
  caseBorder: 1.5
  screwThreadRadius: 0.5
  screwPCBRadius: 4.0

points:
  zones:
    matrix:
      key:
        padding: ky + 2
        spread: kx + 2
      columns:
        shift:
          key:
            column_net: P020
        a:
          key: 
            column_net: P022
        s:
          key:
            stagger: 14
            column_net: P024
        d:
          key:
            stagger: 8
            column_net: P100
        f:
          key:
            stagger: -8
            column_net: P011
          rows.utility.skip: true
        g:
          key:
            column_net: P017
          rows:
            utility:
              skip: true
            anchor: # Explicitly isolate this key's position
                name: utility
                ref: matrix_g_down # Reference the home key position
                shift: [-5, -76] # Shift left only this key
                width: 1.5u
                row_net: P029
      rows:
        utility:
          row_net: P029
        down:
          row_net: P002
        home:
          row_net: P115
        up:
          row_net: P113 
      anchor:
        shift: [100,-150]
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px-4,py-4]
  keys:
    - what: rectangle
      where: true
      size: [14,14]
  board:
    - what: polygon
      operation: stack
      
      fillet: 0
      points:
        - ref: matrix_shift_up
          shift: [-.5px,.5py]
        - ref: matrix_a_up
          shift: [buff,.5py]
        - ref: matrix_s_up
          shift: [-.5px,.5py]
        - ref: matrix_s_up
          shift: [buff,.5py]
        - ref: matrix_d_up
          shift: [-.5px,.5py]
        - ref: matrix_d_up
          shift: [-.5px,.5py]
        - ref: matrix_d_up
          shift: [.5px,.5py]
        - ref: matrix_f_up
          shift: [-buff,.5py]
        - ref: matrix_g_up
          shift: [.5px,.5py]
        - ref: matrix_g_down
          shift: [.5px,-.5py - cy - 2]
        #- ref: matrix_f_down
        #  shift: [-.5px,-.5py - cy -1]
        #- ref: matrix_d_utility
        #  shift: [buff,-.5py]
        #- ref: matrix_d_utility
        #  shift: [-buff,-.5py]
        - ref: matrix_s_utility
          shift: [.5px,-.5py]
        - ref: matrix_s_utility
          shift: [-buff,-.5py]
        - ref: matrix_a_utility
          shift: [.5px,-.5py]
        - ref: matrix_shift_utility
          shift: [-.5px,-.5py]
  combo:
    - name: board
    - operation: subtract
      name: keys
  chip:
    - what: polygon
      operation: stack
      
      points:
        - ref: matrix_shift_up
          shift: [-.5dx,.5dy]
        - ref: matrix_a_up
          shift: [buffs,.5dy]
        - ref: matrix_s_up
          shift: [-.5dx,.5dy]
        - ref: matrix_s_up
          shift: [buffs,.5dy]
        - ref: matrix_d_up
          shift: [-.5dx,.5dy]
        - ref: matrix_d_up
          shift: [-.5dx,.5dy]
        - ref: matrix_d_up
          shift: [.5dx,.5dy]
        - ref: matrix_f_up
          shift: [-buffs,.5dy]
        - ref: matrix_g_up
          shift: [.5dx,.5dy]
        - ref: matrix_g_down
          shift: [.5dx,-.5dy - cy - 2]
        #- ref: matrix_f_down
        #  shift: [-.5px,-.5py - cy -1]
        #- ref: matrix_d_utility
        #  shift: [buff,-.5py]
        #- ref: matrix_d_utility
        #  shift: [-buff,-.5py]
        - ref: matrix_s_utility
          shift: [.5dx,-.5dy]
        - ref: matrix_s_utility
          shift: [-buffs,-.5dy]
        - ref: matrix_a_utility
          shift: [.5dx,-.5dy]
        - ref: matrix_shift_utility
          shift: [-.5dx,-.5dy]
pcbs:
  left:
    outlines:
      main:
        outline: chip
    footprints: 
      choc_hot:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [8.3,-2.5]
          rotate: 90
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where: 
          ref: matrix_g_up
          shift: [-8,-1.5]
          rotate: -180
      switch:
        what: slider
        where:
          ref: utility
          shift: [13,5]
          rotate: -90
        params: 
          side: B
          from: pos
          to: RAW
      reset_button:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: utility
          shift: [13,-4]
          rotate: -90
      battery_jack:
        what: jstph
        where: 
          ref: matrix_d_home
          shift: [0,6]
          rotate: 90
        params:
          side: B
          pos: pos
          neg: GND
      screw_bottom_left:
        what: mountinghole
        where:
          ref: matrix_shift_utility
          shift: [10,8.5]
      screw_top_left:
        what: mountinghole
        where:
          ref: matrix_shift_up
          shift: [10,-10.5]
      screw_middle:
        what: mountinghole
        where: 
          ref: matrix_d_down
          shift: [-8,8]
      screw_bottom_right:
        what: mountinghole
        where: 
          ref: matrix_f_down
          shift: [6,-14]
      screw_top_right:
        what: mountinghole
        where:
          ref: matrix_f_home
          shift: [-8,8]
      front_text:
        what: text
        where: &textWhere
          ref: utility
          shift: [-44,-5]
        params: &textParams
          text: Silikeys
          justify: left
          h_size: 3.0
          v_size: 3.0
          thickness: 0.4